version: "1"

files:
  - in: file.py.tmpl
    out: '{{ .ClassName }}.py'
    fields:
      - ClassName: '{{ .qArgName }}'
        BaseClass: '{{ .qArgBase }}'
        Module: '{{ .qArgModule }}'
        ImportQtCore: '{{ qContains .qArgImport "QtCore" }}'
        ImportQtQuick: '{{ qContains .qArgImport "QtQuick" }}'
        ImportQtWidgets: '{{ qContains .qArgImport "QtWidgets" }}'
