# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
version: 2

project_name: qtcli

env:
  - VERSION=1.5.0
  - CGO_ENABLED=0

builds:
  - id: qtcli
    dir: ./src
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s # strip symbol table
      - -w # strip DWARF debugging information
      - -X main.version={{ .Env.VERSION }}
      - -X main.timestamp={{ .Timestamp }}
      - -X main.commit={{ .FullCommit }}

    binary: >-
      {{ .ProjectName }}_
      {{- .Os }}_
      {{- .Arch }}_
      {{- .Env.VERSION }}
    no_unique_dist_dir: true
    ignore:
      - goos: linux
        goarch: arm64
      - goos: windows
        goarch: arm64

universal_binaries:
  - name_template: >-
      {{ .ProjectName }}_darwin_fat_
      {{- .Env.VERSION }}
    hooks:
      post: cp {{ .Path }} {{ dir .Path }}/../{{ .Name }} # get out of sub-directory

snapshot:
  version_template: '{{ .Env.VERSION }}'

checksum:
  disable: true

archives:
  - format: binary
