version: "1"

files:
  - in: file.h.tmpl
    out: '{{ .FileName }}'
    fields:
      - FileName: '{{ qEnsureExtension .ClassName ".h" }}'
      - HeaderGuard: '{{ .FileName | cpp.CreateHeaderGuard }}'
      - QtMacros: '{{ .qArgAdd }}'
      - UseQtKeyword: true
      - UsePragmaOnce: true

  - in: file.cpp.tmpl
    out: '{{ .FileName }}'
    fields:
      - FileName: '{{ qEnsureExtension .ClassName ".cpp" }}'

global:
  fields:
    - ClassName: '{{ .qArgName | cpp.ExtractClassName }}'
    - BaseClass: '{{ .qArgBase }}'
    - Includes: '{{ cpp.CreateIncludes .qArgInclude .qArgAdd }}'
    - NamespaceOpenings: '{{ .qArgName | cpp.CreateNamespaceOpenings }}'
    - NamespaceClosings: '{{ .qArgName | cpp.CreateNamespaceClosings }}'
    - UseQSharedData: '{{ qContains .Includes "QSharedData" }}'

  header: |
      {{ define "addLicense" }}
        {{- if .qArgLicenseFile }}
        {{- cpp.CreateLicense .qArgLicenseFile .ClassName .FileName }}
        {{- end }}
      {{ end }}
